/** Explicit opt-in examples. Never sent to, or loaded by, the production API. */
import type { Product, Inputs, Observation } from './types';
const observed = '2026-09-06T09:00:00Z';
const series = [24,28,26,34,31,37,42,null,41,48,45,55,58,54,61,67,63,70,74,69,75,78,76,81,83,78,85,89,86,91];
const example = (id: string, metric: string, value: number, unit: string, source: string): Observation => ({ id, metric, value, unit, source, source_url: 'https://trends.google.com/trends/', market: 'US', observed_at: observed, fetched_at: observed, truth_state: 'Demo', confidence: 64, snapshot_id: `demo-snapshot-${id}`, collector_version: 'demo-fixture/1', parser_version: 'demo-fixture/1', usage_rights: 'Synthetic example only — not source evidence', series: metric === 'Search interest' ? series.map((value,index)=>({ date: new Date(Date.UTC(2026,7,8+index)).toISOString().slice(0,10), value })) : undefined });
export const demoProducts: Product[] = [
  {id:'demo-steamer', name:'Portable garment steamer', category:'Home & living', asin:'DEMO000001', source_url:'', market:'NG', confirmed:true, truth_state:'Demo', decision:'WATCH', confidence:64, stage:'Building momentum', blocker:'Import classification still needs review.', observations:[example('d1','Search interest',91,'index / 100','Google Trends example'),example('d2','Review velocity',12,'reviews / week','Marketplace example')], created_at:observed, illustration:'steamer', signals:['Search interest is rising','Review activity is increasing','Local coverage needs validation']},
  {id:'demo-lamp', name:'Sunset projection lamp', category:'Home & living', asin:'DEMO000002', source_url:'', market:'NG', confirmed:true, truth_state:'Demo', decision:'INSUFFICIENT EVIDENCE', confidence:32, stage:'Early signal', blocker:'Local demand and supplier evidence are missing.', observations:[example('d3','Search interest',57,'index / 100','Google Trends example')],created_at:observed, illustration:'lamp', signals:['One demand signal available','No current supplier quote','Destination coverage is limited']},
  {id:'demo-blender', name:'Portable USB blender', category:'Kitchen', asin:'DEMO000003', source_url:'', market:'NG', confirmed:true, truth_state:'Demo', decision:'NO-GO', confidence:71, stage:'Needs a better margin', blocker:'Illustrative base margin is below the 15% gate.', observations:[example('d4','Search interest',43,'index / 100','Google Trends example')],created_at:observed, illustration:'blender', signals:['Demand alone is not enough','Illustrative costs exceed the margin gate','Rework the quote before ordering']},
];
export const demoInputs: Inputs = {quantity:300,unit_cost_usd:8.4,fx_ngn:1500,freight_ngn:900000,duty_pct:5,import_tax_pct:7.5,selling_price_ngn:32000,channel_fee_pct:5,returns_pct:3,marketing_ngn:300000,fixed_cost_ngn:150000,stress_pct:10,compliance:'unresolved',channel:'Direct sales',shipping:'Air'};
