#!/usr/bin/env python3
"""Regenerate the checked-in server/browser economics contract.

The committed JSON remains the review artifact. This command only removes hand-edited
expected values from the workflow: it archives the previously current formula once,
adds every required D02 input explicitly, calculates with the backend implementation,
and emits stable JSON. Frontend and backend tests then replay the artifact independently.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'backend'))

from app.economics import (COST_MODEL_VERSION, FORMULA_VERSION, THRESHOLD_VERSION,
                           Inputs, calculate)  # noqa: E402

CONTRACT = ROOT / 'contracts' / 'economics_cases.json'
V1_1_ARCHIVE = ROOT / 'contracts' / 'economics_v1_1_cases.json'
CURRENT_FIELDS = {
    'packaging_ngn': 0,
    'insurance_ngn': 0,
    'clearance_ngn': 0,
    'local_delivery_ngn': 0,
    'payment_fee_pct': 0,
    'reserve_ngn': 0,
    'fx_buffer_pct': 0,
    'supplier_deposit_pct': 0,
    'cash_tied_up_days': 0,
}
REPRESENTATIVE_D02 = {
    'packaging_ngn': 90_000,
    'insurance_ngn': 75_000,
    'clearance_ngn': 180_000,
    'local_delivery_ngn': 120_000,
    'payment_fee_pct': 1,
    'reserve_ngn': 30_000,
    'fx_buffer_pct': 2,
    'supplier_deposit_pct': 30,
    'cash_tied_up_days': 55,
}


def rendered() -> tuple[str | None, str]:
    previous = json.loads(CONTRACT.read_text())
    archive = None
    if previous['formula_version'] == 'unit-economics/1.1.0' and not V1_1_ARCHIVE.exists():
        archive = json.dumps(previous, indent=2) + '\n'

    cases = []
    for old in previous['cases']:
        inputs = dict(old['inputs'])
        for key, value in CURRENT_FIELDS.items():
            inputs.setdefault(key, value)
        if old['name'] == 'worked-example-no-evidence':
            inputs.update(REPRESENTATIVE_D02)
        expected = calculate(Inputs(**inputs), old['evidence'])
        cases.append({**old, 'inputs': inputs, 'expected': expected})
    current = {
        **{key: value for key, value in previous.items()
           if key not in {'formula_version', 'threshold_version', 'cost_model_version', 'note', 'cases'}},
        'formula_version': FORMULA_VERSION,
        'threshold_version': THRESHOLD_VERSION,
        'cost_model_version': COST_MODEL_VERSION,
        'note': ('Shared decision contract generated by scripts/generate_economics_contract.py. '
                 'Backend and frontend tests must reproduce every case exactly; former '
                 'formula contracts are frozen separately for historical replay.'),
        'cases': cases,
    }
    return archive, json.dumps(current, indent=2) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='fail if the committed contract would change')
    args = parser.parse_args()
    archive, current = rendered()
    if args.check:
        if archive is not None or CONTRACT.read_text() != current:
            print('economics contract is stale', file=sys.stderr)
            return 1
        return 0
    if archive is not None:
        V1_1_ARCHIVE.write_text(archive)
    CONTRACT.write_text(current)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
