import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowDownRight, ArrowRight, ArrowUpRight, Check, ChevronDown, Download, FileCheck2, History, Info, Save, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { toast } from 'sonner';
import { useWorkspace } from '@/shared/Workspace';
import { DecisionBadge, Empty, Loading, Modal, Notice, PageTitle, TruthBadge } from '@/shared/UI';
import { calculate, sensitivity, targets } from '@/lib/economics';
import { dateTime, download, formatMoney } from '@/lib/utils';
import type { Assessment, Inputs, Scenario } from '@/types';

type NumericKey = Exclude<keyof Inputs,'compliance'|'channel'|'shipping'>;
const fieldGroups: {title:string;fields:{key:NumericKey;label:string;unit:string;min:number;max:number;step?:number;help?:string}[]}[]=[
 {title:'Order & supplier',fields:[{key:'quantity',label:'Order quantity',unit:'units',min:1,max:1000000,step:1},{key:'unit_cost_usd',label:'Supplier unit quote',unit:'USD',min:0,max:1000000},{key:'fx_ngn',label:'Your exchange rate',unit:'NGN / USD',min:.0001,max:1000000}]},
 {title:'Freight & import assumptions',fields:[{key:'freight_ngn',label:'Total freight quote',unit:'NGN',min:0,max:1e12},{key:'duty_pct',label:'Duty assumption',unit:'%',min:0,max:100,help:'Applied to supplier value + freight. Confirm the actual assessment basis.'},{key:'import_tax_pct',label:'Import tax assumption',unit:'%',min:0,max:100,help:'Applied to supplier value + freight + duty. Classification remains unreviewed.'}]},
 {title:'Sales & operating costs',fields:[{key:'selling_price_ngn',label:'Target selling price',unit:'NGN / unit',min:.0001,max:1e12},{key:'channel_fee_pct',label:'Channel & payment fees',unit:'%',min:0,max:100},{key:'returns_pct',label:'Returns allowance',unit:'%',min:0,max:100},{key:'marketing_ngn',label:'Total marketing budget',unit:'NGN',min:0,max:1e12},{key:'fixed_cost_ngn',label:'Fixed costs & reserves',unit:'NGN',min:0,max:1e12,help:'Include overhead and any additional tax or launch reserve.'}]},
];
const fields=fieldGroups.flatMap(g=>g.fields);
const initial=()=>Object.fromEntries(fields.map(f=>[f.key,''])) as Record<NumericKey,string>;
export default function DecisionRoom(){
 const w=useWorkspace();const [params,setParams]=useSearchParams();const product=w.products.find(p=>p.id===params.get('product'))||w.products[0];
 const [values,setValues]=useState(initial);const [stress,setStress]=useState(10);const [channel,setChannel]=useState('Direct sales');const [shipping,setShipping]=useState<'Air'|'Sea'>('Air');const [compliance,setCompliance]=useState<'unresolved'|'prohibited'>('unresolved');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState<Assessment|null>(null);const [history,setHistory]=useState(false);const [scenario,setScenario]=useState(1);
 useEffect(()=>{let active=true;setValues(initial());setSaved(null);setCompliance('unresolved');if(w.demo)void import('@/demo').then(({demoInputs})=>{if(active){const data={...demoInputs,selling_price_ngn:product?.id==='demo-blender'?20000:32000};setValues(Object.fromEntries(fields.map(f=>[f.key,String(data[f.key])])) as Record<NumericKey,string>);setStress(data.stress_pct);}});return()=>{active=false;};},[w.demo,product?.id]);
 const valid=fields.every(f=>values[f.key]!==''&&Number.isFinite(+values[f.key])&&+values[f.key]>=f.min&&+values[f.key]<=f.max&&(f.key!=='quantity'||Number.isInteger(+values[f.key])));
 const inputs={...Object.fromEntries(fields.map(f=>[f.key,+values[f.key]])),stress_pct:stress,compliance,channel,shipping} as Inputs;
 const result=useMemo(()=>valid?calculate(inputs,w.demo&&product?{confidence:product.confidence,coverage:product.confidence>=40,compliance_resolved:false,overall:product.id==='demo-blender'?45:64,observation_ids:product.observations.map(o=>o.id)}:undefined):null,[JSON.stringify(inputs),valid,w.demo,product]);
 const active=result?.scenarios[scenario],base=result?.scenarios[1];
 const swings=useMemo(()=>valid?sensitivity(inputs):[],[JSON.stringify(inputs),valid]);
 const goal=useMemo(()=>valid?targets(inputs):null,[JSON.stringify(inputs),valid]);
 const labelOf=(key:NumericKey)=>fields.find(f=>f.key===key)?.label||key;
 const exportDecision=(a:Assessment)=>download(`trendsell-decision-${a.id||'draft'}.json`,JSON.stringify({...a,exported_at:new Date().toISOString(),demo:w.demo,threshold_version:'decision-gates/1.0.0',evidence:product?.observations||[]},null,2));
 if(w.loading)return <Loading/>;
 return <><PageTitle eyebrow="BEFORE YOU COMMIT" title="Make the decision yours." description="Real quotes. Editable assumptions. A clear view of what could go wrong." actions={<button className="button secondary" onClick={()=>setHistory(true)}><History size={16}/>Saved decisions<span className="count-badge">{w.decisions.length}</span></button>}/>
 {!product?<div className="panel"><Empty title="Start with a product worth investigating." action={<Link to="/xray" className="button primary">Analyze a product<ArrowRight size={16}/></Link>}>Decision Room connects a product’s evidence to your commercial assumptions. Capture a product first, or explore the explicitly labeled demo.</Empty></div>:<>
 <div className="decision-toolbar"><label>INVESTIGATING<select aria-label="Choose product" value={product.id} onChange={e=>setParams({product:e.target.value})}>{w.products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="decision-market"><span className="nigeria-flag"/><span>Nigeria</span><span className="muted-text">NGN scenarios</span></div><TruthBadge truth={w.demo?'Demo':'User input'}/></div>
 <Notice kind={w.demo?'amber':'muted'}>{w.demo?'All prefilled figures are illustrative demo assumptions, including FX and import rates. They are not market quotes or regulatory guidance.':'Enter your own quotes, fees, FX, and import assumptions. No rates are supplied automatically. A reviewed classification is required before GO.'}</Notice>
 <div className="decision-room-layout"><section className="panel assumptions"><div className="section-heading"><div><h2>Your commercial inputs</h2><p>All amounts below come from you.</p></div><SlidersHorizontal size={18}/></div><form onSubmit={async e=>{e.preventDefault();if(!result)return;if(!w.requireUser())return;setBusy(true);try{const a=await w.saveDecision(result,product);setSaved(a);toast.success('Decision saved with its exact inputs and formula version');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>
 {fieldGroups.map(g=><fieldset key={g.title}><legend>{g.title}</legend><div className="input-grid">{g.fields.map(f=><label className={f.help?'wide-input':''} key={f.key}>{f.label}<div className="unit-input"><input aria-label={f.label} type="number" required min={f.min} max={f.max} step={f.step||'any'} value={values[f.key]} placeholder="Enter value" onChange={e=>{setValues({...values,[f.key]:e.target.value});setSaved(null);}}/><span>{f.unit}</span></div>{f.help&&<small>{f.help}</small>}</label>)}</div></fieldset>)}
 <fieldset><legend>Route & readiness</legend><div className="input-grid"><label>Sales channel<select value={channel} onChange={e=>setChannel(e.target.value)}>{['Direct sales','Jumia','Konga','Retail / wholesale','Other'].map(c=><option key={c}>{c}</option>)}</select></label><label>Freight mode<select value={shipping} onChange={e=>setShipping(e.target.value as 'Air'|'Sea')}><option>Air</option><option>Sea</option></select></label><label className="wide-input">Import status<select value={compliance} onChange={e=>setCompliance(e.target.value as 'unresolved'|'prohibited')}><option value="unresolved">Classification / requirements unresolved</option><option value="prohibited">Marked prohibited — block launch</option></select><small>A self-entered assumption cannot clear the compliance gate.</small></label></div></fieldset>
 <div className="stress-control"><div><label htmlFor="stress">Scenario stress range</label><strong>±{stress}%</strong></div><input id="stress" aria-label="Scenario stress range" type="range" min="0" max="50" value={stress} onChange={e=>{setStress(+e.target.value);setSaved(null);}}/><p>Downside: selling price falls {stress}%, supplier and freight costs rise {stress}%. Upside reverses those changes. These are scenarios, not forecasts.</p></div>
 <button className="button primary full" type="submit" disabled={!valid||busy||!product.confirmed}><Save size={16}/>{busy?'Saving…':'Save this decision'}</button>{!product.confirmed&&<p className="form-error">Confirm product identity in X-Ray before saving.</p>}
 </form></section><div className="scenario-output">{result&&base&&active?<>
 <section className="panel decision-verdict"><div className="section-heading"><span className="eyebrow">YOUR CURRENT DECISION</span><TruthBadge truth={w.demo?'Demo':'Calculated'}/></div><DecisionBadge decision={result.decision}/><p>{result.decision==='WATCH'?'The economics are a start. Close the evidence gaps before committing.':result.decision==='NO-GO'?'The current assumptions do not pass the decision gates.':'Your scenario is calculated. Demand and import readiness still need evidence.'}</p><div className="verdict-metrics"><div><small>Base contribution margin</small><strong className={base.margin_pct>=25?'text-lime':'text-amber'}>{base.margin_pct.toFixed(1)}<span>%</span></strong></div><div><small>Evidence confidence</small><strong>{result.confidence}<span>/ 100</span></strong></div></div></section>
 <section className="panel scenarios-panel"><div className="section-heading"><h2>Three scenarios. One clearer picture.</h2></div><div className="scenario-cards">{result.scenarios.map((s,i)=><button key={s.name} onClick={()=>setScenario(i)} className={`scenario-card ${i===scenario?'selected':''}`}><span>{s.name}{i===1&&<small>YOUR INPUTS</small>}</span><strong>{formatMoney(s.contribution)}</strong><small>Contribution / unit</small><b className={s.margin_pct<15?'text-rose':s.margin_pct<25?'text-amber':'text-lime'}>{s.margin_pct.toFixed(1)}% margin</b></button>)}</div></section>
 <section className="panel cost-waterfall"><div className="section-heading"><div><h2>Where each naira goes</h2><p>{active.name} scenario · per unit · NGN</p></div><TruthBadge truth="Calculated"/></div><Waterfall scenario={active}/><div className="economics-kpis"><div><small>Cash required for the order</small><strong>{formatMoney(active.cash_required)}</strong></div><div><small>Break-even acquisition cost / unit</small><strong>{formatMoney(active.break_even_cac)}</strong></div><div><small>Units to cover marketing & fixed costs</small><strong>{active.break_even_units===null?'Not achievable':active.break_even_units.toLocaleString()}</strong></div></div><p className="formula-caption">Cash = landed cost × quantity + marketing + fixed costs. CAC headroom includes the fixed-cost allocation. Break-even units assume the entered selling price and all variable costs.</p></section>
 <section className="panel sensitivity-panel"><div className="section-heading"><div><h2>What moves this decision most</h2><p>Base margin swing when one input changes by ±10% and everything else holds.</p></div><TruthBadge truth="Calculated"/></div>{swings.length?<div className="sensitivity-rows">{swings.map(s=><div className="sensitivity-row" key={s.key}><span>{labelOf(s.key)}</span><div className="sensitivity-track"><i style={{width:`${Math.min(100,s.swing/swings[0].swing*100)}%`}}/></div><strong>{s.swing.toFixed(1)}<small>pts</small></strong><small>−10% → {s.low.toFixed(1)}% · +10% → {s.high.toFixed(1)}%</small></div>)}</div>:<p className="muted-text">No input changes the margin at these values.</p>}<p className="formula-caption">Each row re-runs the same formula with one input changed. These are scenarios for prioritising your next question, not forecasts.</p></section><section className="panel blockers-panel"><div className="section-heading"><h2>What must become true?</h2><ShieldCheck size={19}/></div>{result.blockers.map((b,i)=><div className="blocker-item" key={b}><span>{i+1}</span><p>{b}</p></div>)}{goal&&base.margin_pct<goal.target_margin&&<div className="target-note"><h4>To reach a {goal.target_margin}% base margin</h4><p>At {inputs.quantity.toLocaleString()} units, either raise the selling price to {goal.price===null?"a price these fees and returns cannot support":formatMoney(goal.price)}{goal.max_landed!==null?<> or bring the landed cost below {formatMoney(goal.max_landed)} per unit{goal.max_unit_cost_usd!==null?<> — about {formatMoney(goal.max_unit_cost_usd,"USD")} per unit from the supplier at your exchange rate</>:null}</>:null}. Your current landed cost is {formatMoney(goal.landed)} per unit.</p></div>}<Link to="/data-health" className="text-button">Review the missing evidence<ArrowUpRight size={15}/></Link></section>
 <div className="formula-note"><FileCheck2 size={17}/><span>Reproducible by design.<small>{result.formula_version} · NGN · exact inputs saved with each assessment</small></span><button className="text-button" onClick={()=>exportDecision(saved||result)}><Download size={15}/>{saved?'Export saved decision':'Export draft'}</button></div>{saved&&<Notice>Saved {dateTime(saved.created_at)}. This assessment is immutable; further changes create a new saved decision.</Notice>}
 </>:<section className="panel"><Empty title="Your inputs unlock the economics.">Fill in each commercial input, including zero for any cost that does not apply. We won’t fill missing costs with guesses.</Empty><div className="input-progress"><span>{fields.filter(f=>values[f.key]!=='').length} of {fields.length} inputs added</span><div><i style={{width:`${fields.filter(f=>values[f.key]!=='').length/fields.length*100}%`}}/></div></div></section>}</div></div></>}
 <Modal open={history} onOpenChange={setHistory} title="Saved decisions" description="Immutable snapshots of your assumptions and calculated results." drawer>{w.decisions.length?w.decisions.map(d=><div className="saved-decision" key={d.id}><div><h3>{d.product_name}</h3><p>{dateTime(d.created_at)}</p></div><DecisionBadge decision={d.decision}/><dl><div><dt>Formula</dt><dd>{d.formula_version}</dd></div><div><dt>Base margin</dt><dd>{d.scenarios[1].margin_pct}%</dd></div></dl><TruthBadge truth={d.truth_state}/><button className="button secondary full" onClick={()=>exportDecision(d)}><Download size={15}/>Download assessment</button></div>):<Empty title="No saved decisions yet">Complete a scenario and save it to preserve the exact inputs, evidence references, and calculation version.</Empty>}</Modal></>;
}
function Waterfall({scenario:s}:{scenario:Scenario}){
 const rows:[string,number,string][]=[['Target selling price',s.price,'price'],['Supplier quote',s.supplier,'cost'],['Freight allocation',s.freight,'cost'],['Duty assumption',s.duty,'cost'],['Import tax assumption',s.import_tax,'cost'],['Channel & payment fees',s.fees,'cost'],['Returns allowance',s.returns,'cost'],['Marketing allocation',s.marketing,'cost'],['Fixed-cost allocation',s.overhead,'cost'],['Contribution per unit',s.contribution,'total']];
 return <div className="waterfall-rows">{rows.map(([name,value,type])=><div key={name} className={`waterfall-row ${type}`}><span>{name}</span><div className="waterfall-track"><i style={{width:`${Math.min(Math.abs(value)/s.price*100,100)}%`}}/></div><strong>{formatMoney(value)}</strong></div>)}</div>;
}
