import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Activity, ArrowRight, ArrowUpRight, Bell, BellOff, Check, ChevronDown, Download, ExternalLink, FilePlus2, FileText, FlaskConical, Globe2, LogOut, Plus, RefreshCw, Settings as SettingsIcon, ShieldCheck, SlidersHorizontal, Trash2, Truck, UserPlus, Users } from 'lucide-react';
import { toast } from 'sonner';
import { useWorkspace } from '@/shared/Workspace';
import { AccountSecurity } from '@/features/Account';
import { AssessmentSummary, DecisionBadge, Empty, Loading, Modal, Notice, PageTitle, ProductPicker, TruthBadge } from '@/shared/UI';
import { api, del, post } from '@/lib/api';
import { dateTime, download, formatMoney } from '@/lib/utils';
import type { Source, User, Watch, WorkspaceInvitation } from '@/types';

export function DataHealth(){
 const w=useWorkspace();const [filter,setFilter]=useState('All sources');
 const query=useQuery({queryKey:['data-health'],queryFn:()=>api<{sources:Source[];coverage:number|null}>('/data-health'),retry:false});
 const sources=(query.data?.sources||[]).filter(s=>filter==='All sources'||s.markets.includes('NG'));
 const connected=query.data?.sources.filter(s=>s.status==='connected').length||0;
 const configured=query.data?.sources.some(s=>['configured','connected','collecting','degraded'].includes(s.status))||false;
 const lastSuccess=query.data?.sources.map(s=>s.last_success).filter(Boolean).sort().at(-1)||null;
 return <><PageTitle eyebrow="TRUST IS A FEATURE" title="Know what your data knows." description="Source coverage, freshness, and limitations. Nothing hidden behind a score." actions={<button className="button secondary" disabled={query.isFetching} onClick={()=>void query.refetch()}><RefreshCw size={15} className={query.isFetching?'spin':''}/>Check status</button>}/>
 {query.error?<Notice kind="amber">Source health is unavailable: {query.error.message}</Notice>:<Notice>{configured?'A server-side catalog connection is configured. Its latest workspace attempt is shown below.':'Live collectors are not connected in this workspace.'} There is no automatic refresh, and no synthetic fallback when evidence is missing.</Notice>}
 <div className="health-summary">{[{label:'Connected sources',value:query.data?`${connected} / ${query.data.sources.length}`:'—',text:'Latest user-requested checks'},{label:'Destination coverage',value:'Insufficient',text:'Nigeria · collection required'},{label:'Last successful collection',value:lastSuccess?dateTime(lastSuccess):'No observations',text:lastSuccess?'Current catalog collection only':'Freshness cannot yet be assessed'}].map(s=><div className="panel" key={s.label}><small>{s.label}</small><strong>{s.value}</strong><p>{s.text}</p></div>)}</div><div className="section-heading"><h2>Your evidence sources</h2><div className="segmented">{['All sources','Nigeria sources'].map(s=><button key={s} className={s===filter?'selected':''} onClick={()=>setFilter(s)}>{s}</button>)}</div></div>
 {query.isLoading?<Loading/>:<div className="source-grid">{sources.map((s,i)=><article className="panel source-card" key={s.id}><div className="source-head"><span className={`source-icon source-${i}`}>{s.id==='amazon'?'a':s.id==='google_trends'?<Activity size={23}/>:s.id==='compliance'?<ShieldCheck size={23}/>:s.id==='freight'?<Truck size={23}/>:<Globe2 size={23}/>}</span><div><h3>{s.name}</h3><p>{s.category}</p></div><span className="status-label">{s.status}</span></div><p className="source-reason">{s.reason}</p><dl className="source-meta"><div><dt>Markets</dt><dd>{s.markets.join(' · ')}</dd></div><div><dt>Last success</dt><dd>{s.last_success?dateTime(s.last_success):'No successful collection'}</dd></div><div><dt>Last attempt</dt><dd>{s.last_attempt?dateTime(s.last_attempt):'Not attempted'}</dd></div><div><dt>Next retry</dt><dd>{s.next_retry}</dd></div><div><dt>Usage rights</dt><dd>{s.rights}</dd></div></dl><div className="source-footer"><TruthBadge truth={s.status==='connected'?'Observed':'Unavailable'}/><span>Target freshness: {s.freshness_hours}h</span></div></article>)}</div>}
 <div className="panel evidence-policy"><div className="section-icon lime"><ShieldCheck size={22}/></div><div><h3>Our evidence promise</h3><p>Observed facts retain their source. Calculations retain their inputs. Estimates show their method. Missing evidence stays missing.</p><div className="truth-legend">{(['Observed','Calculated','Estimated','User input','Unavailable','Demo'] as const).map(t=><TruthBadge key={t} truth={t}/>)}</div></div></div></>;
}
export function Watchtower(){
 const w=useWorkspace();const [editing,setEditing]=useState<Watch|null>(null);const [threshold,setThreshold]=useState(15);const [busy,setBusy]=useState(false);
 return <><PageTitle eyebrow="KEEP THE RIGHT THINGS IN VIEW" title="Your watchlist." description="Save an investigation now. Revisit it when the evidence is ready." actions={<Link className="button primary" to="/discover"><Plus size={16}/>Find a product to watch</Link>}/><Notice>This is a saved watchlist, not monitoring: no collector runs on a schedule and no notification is delivered. Your rule is stored for when collection is enabled.</Notice><div className="section-heading"><h2>Watched products<span className="count-badge">{w.watchTotal}</span></h2><span className="muted-text">In-app watch rules</span></div>
 {w.loading?<Loading/>:w.watches.length?<><div className="watch-list">{w.watches.map(watch=>{const p=w.products.find(p=>p.id===watch.product_id);return <article className="panel watch-row" key={watch.id}><div className="watch-icon"><Bell size={23}/></div><div className="watch-main"><Link to={`/products/${watch.product_id}`}><h3>{p?.name||watch.product_name||'Product investigation'}<ArrowUpRight size={14}/></h3></Link><p>Materiality threshold: {watch.threshold_pct}% · Nigeria</p><span className="status-label">Awaiting source collection</span></div><div className="watch-verdicts"><span><small>Evidence</small><DecisionBadge decision={p?.decision||watch.product_decision||'INSUFFICIENT EVIDENCE'}/></span><span><small>Your latest assessment</small><AssessmentSummary assessment={p?.latest_assessment??watch.latest_assessment} compact/></span></div><button className="button secondary" onClick={()=>{setEditing(watch);setThreshold(watch.threshold_pct);}}><SlidersHorizontal size={15}/>Edit rule</button><button className="icon-button" aria-label={`Remove ${p?.name||watch.product_name||'product'} from your watchlist`} onClick={async()=>{try{await w.unwatch(watch.id);toast.success('Removed from your watchlist');}catch(e){toast.error((e as Error).message);}}}><Trash2 size={16}/></button></article>;})}</div><div className="page-more"><span className="muted-text">Showing {w.watches.length} of {w.watchTotal} watched products.</span>{w.moreWatches&&<button className="button secondary" disabled={w.loadingMoreWatches} onClick={w.loadMoreWatches}>{w.loadingMoreWatches?'Loading…':'Load more'}</button>}</div></>:<div className="panel"><Empty title="Some ideas are worth keeping an eye on." action={<Link to="/discover" className="button secondary">Explore your investigations<ArrowRight size={15}/></Link>}>Add products to your watchlist to save your interest and a material-change threshold. Nothing is collected or alerted on yet.</Empty></div>}
 <div className="section-heading spaced"><h2>Material changes</h2><span className="truth"><span/>Monitoring unavailable</span></div><div className="quiet-feed panel"><BellOff size={25}/><div><h3>Monitoring is not enabled.</h3><p>Nothing is being collected or checked, so an empty feed here means no monitoring rather than no change. When scheduled collection is enabled, alerts will cite the before and after values, their source and time, and the decision impact.</p></div></div>
 <Modal open={!!editing} onOpenChange={open=>!open&&setEditing(null)} title="Edit watch rule" description="Choose the change worth coming back for."><form className="stack" onSubmit={async e=>{e.preventDefault();if(!editing)return;setBusy(true);try{await w.watch(editing.product_id,threshold);setEditing(null);toast.success('Watch rule saved');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}><label>Materiality threshold (%)<input type="number" min={1} max={100} required value={threshold} onChange={e=>setThreshold(+e.target.value)}/></label><Notice>Collection is paused. Saving this rule does not enable scheduled monitoring or delivery.</Notice><button className="button primary" disabled={busy}>Save rule<Check size={16}/></button></form></Modal></>;
}
export function Suppliers(){
 const w=useWorkspace();const [open,setOpen]=useState(false);const [rfq,setRfq]=useState(false);const [busy,setBusy]=useState(false);const [draft,setDraft]=useState('');
 return <><PageTitle eyebrow="TURN RESEARCH INTO REAL CONVERSATIONS" title="Better sourcing starts with a quote." description="Keep supplier-provided costs separate from assumptions. Compare what you actually know." actions={<><button className="button secondary" onClick={()=>{if(w.requireUser())setRfq(true);}}><FileText size={16}/>Draft an RFQ</button><button className="button primary" onClick={()=>{if(w.requireUser())setOpen(true);}}><Plus size={16}/>Add a quote</button></>}/><Notice>Supplier records are user-created candidates. Certificates, reliability, and prices are not independently verified. No messages are sent by TrendSell.</Notice>
 <div className="section-heading"><h2>Your quote room<span className="count-badge">{w.quoteTotal}</span></h2><span className="muted-text">Dated inputs, clearer comparisons</span></div>{w.quotes.length?<><div className="panel table-scroll"><table><thead><tr><th>Supplier / product</th><th>Unit quote</th><th>MOQ</th><th>Lead time</th><th>Terms / date</th><th>Evidence</th></tr></thead><tbody>{w.quotes.map(q=><tr key={q.id}><td><a className="table-link" href={q.source_url} target="_blank" rel="noreferrer">{q.supplier}<ExternalLink size={13}/></a><small>{w.products.find(p=>p.id===q.product_id)?.name||q.product_name}</small></td><td>{formatMoney(q.unit_price??q.unit_price_usd??0,q.currency||'USD')}</td><td>{q.moq} units</td><td>{q.lead_days} days</td><td>{q.incoterm}<small>{q.quote_date}</small></td><td><TruthBadge truth={q.truth_state}/><small>Unverified</small></td></tr>)}</tbody></table></div><div className="page-more"><span className="muted-text">Showing {w.quotes.length} of {w.quoteTotal} quotes.</span>{w.moreQuotes&&<button className="button secondary" disabled={w.loadingMoreQuotes} onClick={w.loadMoreQuotes}>{w.loadingMoreQuotes?'Loading…':'Load more'}</button>}</div></>:<div className="panel"><Empty title="A real quote is worth a thousand estimates." action={<button className="button primary" onClick={()=>{if(w.requireUser())setOpen(true);}}><FilePlus2 size={16}/>Add your first quote</button>}>Record a supplier’s identity, source link, dated unit price, currency, and terms. We’ll keep the original inputs intact as you test the economics.</Empty></div>}
 <div className="sourcing-steps">{[['01','Define the request','Build an RFQ from your confirmed product and required quantity.'],['02','Capture the quote','Keep the supplier’s source, date, price, and Incoterm together.'],['03','Test the landed cost','Use the quote in a scenario and include freight, duties, and fees.']].map(([n,title,text])=><div className="panel" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div>
 <Modal open={open} onOpenChange={setOpen} title="Record a supplier quote" description="Enter the exact information the supplier gave you.">{!w.productTotal?<Empty title="Capture a product first" action={<Link to="/xray" onClick={()=>setOpen(false)} className="button primary">Open X-Ray</Link>}>Quotes belong to a product investigation.</Empty>:<form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);const d=new FormData(e.currentTarget);try{await w.saveQuote({product_id:String(d.get('product')),supplier:String(d.get('supplier')),source_url:String(d.get('url')),unit_price:Number(d.get('price')),currency:String(d.get('currency')),moq:Number(d.get('moq')),lead_days:Number(d.get('lead')),quote_date:String(d.get('date')),incoterm:String(d.get('incoterm')),notes:String(d.get('notes'))});setOpen(false);toast.success('Quote recorded as unverified user input');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}><ProductPicker name="product"/><label>Supplier name<input name="supplier" minLength={2} maxLength={200} required placeholder="Company name from the quote"/></label><label>Supplier or quote source URL<input name="url" type="url" pattern="https://.*" maxLength={2000} required placeholder="https://"/></label><div className="input-grid"><label>Unit price<input name="price" aria-label="Unit price" type="number" min="0.01" max="1000000" step="0.01" required/></label><label>Currency<select name="currency" aria-label="Quote currency" defaultValue="USD"><option>USD</option><option>CNY</option><option>NGN</option></select></label><label>Minimum order (units)<input name="moq" type="number" min="1" max="1000000" required/></label><label>Lead time (days)<input name="lead" type="number" min="1" max="1000" required/></label><label>Quote date<input name="date" type="date" max={new Date().toISOString().slice(0,10)} required/></label><label>Incoterm<select name="incoterm">{['FOB','EXW','CIF','DDP'].map(t=><option key={t}>{t}</option>)}</select></label></div><label>Notes & validity<textarea name="notes" maxLength={2000} placeholder="Expiry, packaging, certificates supplied, or unanswered questions"/></label><button className="button primary" disabled={busy}>{busy?'Saving…':'Save quote'}<Check size={16}/></button></form>}</Modal>
 <Modal open={rfq} onOpenChange={setRfq} title="Draft a request for quotation" description="A user-editable draft. Download it to review and send yourself."><form className="stack" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const d=new FormData(form);
   // The picker searches the server, so the chosen product need not be in a loaded page.
   // Its own option carries the confirmed name, which is the only field the draft uses.
   const select=form.elements.namedItem('product') as HTMLSelectElement;
   const p={name:select.options[select.selectedIndex]?.text ?? ''};
   if(!p.name)return;setDraft(`${w.demo?'DEMO DRAFT — SYNTHETIC PRODUCT\n\n':''}Subject: Request for quotation — ${p.name}\n\nHello,\n\nPlease provide a written quotation for the following:\n\nProduct: ${p.name}\nQuantity: ${d.get('quantity')} units\nDestination: Nigeria\nSpecifications: ${d.get('specifications')}\n\nPlease include your company details, dated unit price, currency, MOQ, Incoterm, packaging dimensions, sample cost, production lead time, payment terms, and quote validity. Please list any certificates you can supply, with their issuing authority and product reference, for independent review.\n\nNo order is confirmed by this request. We will review specifications, import requirements, and shipping costs before proceeding.\n\nThank you.`);}}><ProductPicker name="product" confirmedOnly/><label>Required quantity<input name="quantity" type="number" min={1} max={1000000} required/></label><label>Required specifications<textarea name="specifications" required maxLength={2000} placeholder="Describe materials, dimensions, packaging, and any requirements you have confirmed."/></label><button className="button secondary" type="submit"><FileText size={15}/>Generate draft</button>{draft&&<><label>Review and edit<textarea className="rfq-text" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="button primary" type="button" onClick={()=>download('trendsell-rfq-draft.txt',draft,'text/plain')}><Download size={15}/>Download draft</button><p className="form-caption">Nothing has been sent to a supplier.</p></>}</form></Modal></>;
}

function WorkspaceMembers(){
 const w=useWorkspace();const [busy,setBusy]=useState(false);
 const enabled=!w.demo&&w.user?.role==='owner';
 const query=useQuery({queryKey:['workspace-members'],queryFn:()=>api<{members:User[];invitations:WorkspaceInvitation[]}>('/workspace/members'),enabled,retry:false});
 if(!enabled)return null;
 const refresh=async()=>{await query.refetch();};
 return <section className="panel settings-card workspace-members-card"><div className="section-heading"><div><h2>Pilot members & review roles</h2><p>Pilot access is granted only through an owner-issued email invitation.</p></div><Users size={19}/></div>
  <form className="member-invite-form" onSubmit={async event=>{event.preventDefault();setBusy(true);const form=event.currentTarget;const data=new FormData(form);try{await post('/workspace/invitations',{email:data.get('email'),role:data.get('role')});form.reset();await refresh();toast.success('Invitation sent');}catch(problem){toast.error((problem as Error).message);}finally{setBusy(false);}}}>
   <label>Email address<input name="email" type="email" required maxLength={254} autoComplete="off" placeholder="reviewer@company.com"/></label>
   <label>Role<select name="role" defaultValue="reviewer"><option value="reviewer">Reviewer</option><option value="analyst">Analyst</option><option value="viewer">Viewer</option></select></label>
   <button className="button primary" disabled={busy}><UserPlus size={15}/>{busy?'Sending…':'Invite member'}</button>
  </form>
  {query.error&&<Notice kind="amber">Member list is unavailable: {query.error.message}</Notice>}
  {query.isLoading?<Loading/>:<div className="table-scroll"><table><thead><tr><th>Member</th><th>Role</th><th>Status</th><th/></tr></thead><tbody>
   {(query.data?.members||[]).map(member=><tr key={member.id}><td>{member.email}<small>{member.name}</small></td><td>{member.role==='owner'?<span>Owner</span>:<select aria-label={`Role for ${member.email}`} value={member.role} onChange={async event=>{try{await post(`/workspace/members/${member.id}/role`,{role:event.target.value});await refresh();toast.success('Member role updated');}catch(problem){toast.error((problem as Error).message);}}}><option value="reviewer">Reviewer</option><option value="analyst">Analyst</option><option value="viewer">Viewer</option></select>}</td><td>{member.email_verified?'Verified':'Verification pending'}</td><td>{member.role!=='owner'&&<button className="icon-button" aria-label={`Remove ${member.email} from workspace`} onClick={async()=>{if(!window.confirm(`Remove ${member.email} from this workspace? Their sessions will end immediately.`))return;try{await del(`/workspace/members/${member.id}`);await refresh();toast.success('Member access removed');}catch(problem){toast.error((problem as Error).message);}}}><Trash2 size={15}/></button>}</td></tr>)}
   {(query.data?.invitations||[]).map(invitation=><tr key={invitation.id}><td>{invitation.email}<small>Invited {dateTime(invitation.created_at)}</small></td><td>{invitation.role}</td><td>Pending until {dateTime(invitation.expires_at)}</td><td><button className="icon-button" aria-label={`Revoke invitation for ${invitation.email}`} onClick={async()=>{try{await del(`/workspace/invitations/${invitation.id}`);await refresh();toast.success('Invitation revoked');}catch(problem){toast.error((problem as Error).message);}}}><Trash2 size={15}/></button></td></tr>)}
  </tbody></table></div>}
 </section>;
}

export function Settings(){
 const w=useWorkspace();const [busy,setBusy]=useState(false);
 return <><PageTitle eyebrow="YOUR WORKSPACE, YOUR CONTEXT" title="Set yourself up for clearer decisions." description="A focused pilot market, private research, and transparent source coverage."/><div className="settings-grid"><section className="panel settings-card"><div className="section-heading"><h2>Workspace</h2><SettingsIcon size={18}/></div><dl className="metadata"><div><dt>Name</dt><dd>{w.demo?'Demo workspace':w.user?.name||'Not signed in'}</dd></div><div><dt>Mode</dt><dd>{w.demo?'Demo · synthetic examples':'Free · invitation-only controlled pilot'}</dd></div><div><dt>Role</dt><dd>{w.demo?'Demo explorer':w.user?.role||'Guest'}</dd></div><div><dt>Email</dt><dd>{w.user?.email||'—'}</dd></div></dl>{w.user?<button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await w.signOut();toast.success('Signed out');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}><LogOut size={15}/>Sign out</button>:w.demo?<button className="button secondary" onClick={w.exitDemo}>Exit demo<ArrowRight size={15}/></button>:<button className="button primary" onClick={()=>w.setAuthOpen(true)}>Sign in to your workspace<ArrowRight size={15}/></button>}</section><section className="panel settings-card"><div className="section-heading"><h2>Market & currency</h2><Globe2 size={18}/></div><dl className="metadata"><div><dt>Destination</dt><dd><span className="nigeria-flag"/> Nigeria</dd></div><div><dt>Sourcing origin</dt><dd>China</dd></div><div><dt>Discovery market</dt><dd>Amazon US</dd></div><div><dt>Decision currency</dt><dd>NGN · user-entered FX</dd></div></dl><p className="muted-text">The pilot supports one corridor. New destinations need maintained local sources, tariff records, and coverage owners.</p></section><section className="panel settings-card"><div className="section-heading"><h2>Evidence & integrations</h2><ShieldCheck size={19}/></div><p>No provider credentials are accepted in the browser. Source connections and effective-dated rules require server-side configuration and review.</p><Link to="/data-health" className="button secondary">Review source health<ArrowUpRight size={15}/></Link></section><section className="panel settings-card"><div className="section-heading"><h2>Explore & export</h2><FlaskConical size={19}/></div><p>Demo examples are stored separately in this browser. Saved workspace decisions retain their inputs and formula versions.</p><div className="stack">{!w.demo&&<button className="button secondary" onClick={()=>void w.enterDemo()}>Explore demo workspace<ArrowUpRight size={15}/></button>}{(w.demo||w.user?.role==='owner')&&<button className="button secondary" onClick={async()=>{try{if(w.demo){download('trendsell-demo-workspace-export.json',JSON.stringify({demo:true,schema:'trendsell-demo-export/1',exported_at:new Date().toISOString(),market:'NG',products:w.products,decisions:w.decisions,quotes:w.quotes,watches:w.watches},null,2));return;}
   // The server export walks every authorised record; the loaded pages are only a view of it (T05).
   const body=await api<Record<string,unknown>>('/export');download(`trendsell-workspace-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(body,null,2));toast.success('Workspace export downloaded');}catch(e){toast.error((e as Error).message);}}}><Download size={15}/>Export workspace records</button>}</div></section>
 <WorkspaceMembers/><AccountSecurity/></div></>;
}
