import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Activity, ArrowRight, ArrowUpRight, Bell, CheckCheck, ChevronRight, CircleHelp, Clock3, Compass, FileCheck2, Globe2, Link2, Plus, ScanLine, ShieldCheck, Sparkles } from 'lucide-react';
import { useWorkspace } from '@/shared/Workspace';
import { Empty, EvidenceDrawer, Loading, ProductCard } from '@/shared/UI';
import type { Observation } from '@/types';

export function CaptureInput({large=false}:{large?:boolean}){
 const [input,setInput]=useState('');const navigate=useNavigate();
 return <form className={`capture-form ${large?'large':''}`} onSubmit={e=>{e.preventDefault();navigate(`/xray${input?`?input=${encodeURIComponent(input)}`:''}`);}}><Link2 size={19}/><input aria-label="Product URL or ASIN" value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste an Amazon product URL or ASIN…"/><button className="button primary" type="submit"><ScanLine size={16}/><span>Analyze product</span><ArrowRight size={16}/></button></form>;
}
export default function Today(){
 const w=useWorkspace();const [evidence,setEvidence]=useState<Observation|null>(null);
 const go=w.decisions.filter(d=>d.decision==='GO').length;
 const date=new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'});
 return <div className="today-page"><div className="today-heading"><div className="eyebrow"><span className="small-dot lime"/>YOUR OPPORTUNITY BRIEF</div><span><Clock3 size={13}/>{date}</span></div>
 <section className="hero"><div className="hero-content"><div className="hero-kicker"><Sparkles size={14}/>A little more clarity. A lot less guesswork.</div><h1>Follow the evidence.<br/><span>Find your next move.</span></h1><p>Turn a product idea into a decision you can stand behind.<br className="desktop-break"/> Real signals, transparent economics, and every missing piece.</p><CaptureInput large/><div className="capture-hints"><span><ShieldCheck size={13}/>Evidence you can inspect</span><span><Globe2 size={13}/>Built for the Nigeria corridor</span><Link to="/xray">What can I analyze?<CircleHelp size={12}/></Link></div></div><div className="hero-radar" aria-hidden="true"><div className="radar-orbit orbit-1"/><div className="radar-orbit orbit-2"/><div className="radar-orbit orbit-3"/><div className="radar-cross cross-x"/><div className="radar-cross cross-y"/><div className="radar-sweep"/><div className="radar-center"><ScanLine size={31}/></div><div className="radar-node node-a"><Activity size={18}/></div><div className="radar-node node-b"><ShieldCheck size={17}/></div><div className="radar-node node-c"><Globe2 size={18}/></div><div className="radar-label"><span/>CONNECT THE SIGNALS</div></div></section>
 <section className="summary-grid" aria-label="Workspace summary">{[{icon:Compass,value:w.products.length,label:'Products under investigation',detail:w.demo?'Illustrative research collection':'Your captured product ideas',path:'/discover',color:'lime'},{icon:FileCheck2,value:go,label:'Decisions ready to act on',detail:'All evidence and margin gates met',path:'/decisions',color:'teal'},{icon:CircleHelp,value:w.products.filter(p=>p.decision!=='GO').length,label:'Investigations needing evidence',detail:'A missing piece, a clear next step',path:'/data-health',color:'amber'},{icon:Bell,value:w.watches.length,label:'Products on your watchlist',detail:'Saved for your next review',path:'/watchtower',color:'purple'}].map(({icon:Icon,...s})=><Link className="summary-card" to={s.path} key={s.label}><div className={`summary-icon ${s.color}`}><Icon size={19}/></div><div className="summary-value">{s.value.toString().padStart(2,'0')}<ArrowUpRight size={15}/></div><h3>{s.label}</h3><p>{s.detail}</p></Link>)}</section>
 <div className="today-columns"><div className="opportunities"><div className="section-heading"><div><h2>{w.demo?'On your radar':'Your next opportunities'}<span className="count-badge">{w.products.length}</span></h2><p>{w.demo?'Three example investigations. See how the evidence shapes each decision.':'Investigate an idea, see the evidence, decide what comes next.'}</p></div><Link className="text-button" to="/discover">View all<ArrowRight size={14}/></Link></div>
 {w.loading?<Loading/>:w.products.length?<div className="product-grid today-products">{w.products.slice(0,3).map(p=><ProductCard key={p.id} product={p} onEvidence={setEvidence}/>)}</div>:<div className="panel welcome-panel"><Empty title="Your next opportunity starts with one idea." action={<div className="empty-actions"><Link className="button primary" to="/xray"><Plus size={16}/>Analyze your first product</Link><button className="button secondary" onClick={()=>void w.enterDemo()}>Explore a demo<ArrowUpRight size={15}/></button></div>}>Paste a product URL to start an investigation. We’ll show what’s supported by evidence, what’s missing, and what to do next.</Empty><div className="journey-strip">{['Capture a product','Inspect the proof','Make your decision'].map((t,i)=><div key={t}><span>0{i+1}</span>{t}{i<2&&<ChevronRight size={14}/>}</div>)}</div></div>}
 <Link className="coverage-strip" to="/data-health"><div className="coverage-strip-icon"><ShieldCheck size={20}/></div><div><strong>A clear view includes the blind spots.</strong><p>Live demand, local supply, and compliance sources need connection or review.</p></div><span>Check data coverage<ArrowUpRight size={15}/></span></Link></div>
 <aside className="activity-rail"><div className="section-heading"><div><h2>Your next steps</h2><p>Less noise. More direction.</p></div></div><div className="panel next-steps">{[{icon:ScanLine,title:w.products.length?'Review your product evidence':'Start with a product',text:w.products.length?'Check what supports each signal and what is still missing.':'An Amazon link is all you need to start an investigation.',path:w.products.length?`/products/${w.products[0].id}`:'/xray',label:w.products.length?'Inspect evidence':'Open Product X-Ray'},{icon:Globe2,title:'Know your destination',text:'Nigeria is the pilot destination. Local coverage is visible, never assumed.',path:'/market-gaps',label:'Explore market coverage'},{icon:CheckCheck,title:'Make the numbers yours',text:'Add a real quote and freight cost. Test the downside before committing.',path:'/decisions',label:'Open Decision Room'}].map(({icon:Icon,...s},i)=><div className="next-step" key={s.title}><div className="step-line"><span className={`step-icon step-${i}`}><Icon size={17}/></span>{i<2&&<i/>}</div><div><h3>{s.title}</h3><p>{s.text}</p><Link to={s.path}>{s.label}<ArrowUpRight size={13}/></Link></div></div>)}</div><div className="quiet-card"><Activity size={17}/><h4>No verified changes yet</h4><p>New observations will appear here when collection is connected. A failed source is never treated as falling demand.</p></div></aside></div>
 <EvidenceDrawer observation={evidence} onClose={()=>setEvidence(null)}/></div>;
}
