import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Check, CircleDashed, Clock3, Globe2, Image, Info, Link2, LoaderCircle, ScanLine, ShieldCheck, TextSearch, Video } from 'lucide-react';
import { toast } from 'sonner';
import { useWorkspace } from '@/shared/Workspace';
import { Notice, PageTitle, TruthBadge } from '@/shared/UI';
import { api, post } from '@/lib/api';
import { dateTime } from '@/lib/utils';
import { parseAmazon } from '@/lib/identifier';
import type { Job } from '@/types';

export default function Xray(){
 const w=useWorkspace();const [params]=useSearchParams();const [input,setInput]=useState(params.get('input')||'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [jobId,setJobId]=useState('');const [demoJob,setDemoJob]=useState<Job|null>(null);const [name,setName]=useState('');const [confirmed,setConfirmed]=useState(false);
 const query=useQuery({queryKey:['job',jobId],queryFn:()=>api<Job>(`/research-jobs/${jobId}`),enabled:!!jobId&&!w.demo,refetchInterval:q=>['queued','running'].includes(q.state.data?.status||'queued')?1000:false});
 const job=w.demo?demoJob:query.data;const product=w.products.find(p=>p.id===job?.product_id);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setConfirmed(false);try{parseAmazon(input);}catch(e){setError((e as Error).message);return;}if(!w.requireUser())return;setBusy(true);try{
  if(w.demo){const {demoProducts}=await import('@/demo');const p={...demoProducts[0],confirmed:false};w.addDemoProduct(p);setName(p.name);setDemoJob({id:'demo-job',product_id:p.id,status:'partial',events:[{id:1,step:'Example investigation loaded',status:'succeeded',detail:'The garment steamer is a synthetic demonstration. Your input is not fetched or matched to a real product.',at:new Date().toISOString()},{id:2,step:'Demo evidence attached',status:'succeeded',detail:'Illustrative search and review values are labeled Demo.',at:new Date().toISOString()},{id:3,step:'Live source collection',status:'unavailable',detail:'No external collectors run in demo mode.',at:new Date().toISOString()}]});}
  else{const result=await post<Job>('/xray',{input,market:'NG'},crypto.randomUUID());setJobId(result.id);await w.refresh();setName('');}
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><PageTitle eyebrow="FROM IDEA TO INVESTIGATION" title="Put a product under the X-Ray." description="Start with an identifier. Confirm the match. Follow the evidence."/><div className="xray-layout"><div><section className="panel xray-capture"><div className="tab-bar"><span className="tab active"><Link2 size={15}/>URL or ASIN</span>{[{icon:Image,label:'Image'},{icon:Video,label:'Video'},{icon:TextSearch,label:'Keyword'}].map(({icon:Icon,label})=><span className="tab unavailable" key={label} title="Not available in the pilot"><Icon size={15}/>{label}<small>Later</small></span>)}</div><form onSubmit={submit} className="xray-form"><label htmlFor="xray-input">What are you investigating?</label><div className="xray-input"><ScanLine size={23}/><input id="xray-input" required value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste an Amazon US product URL or ASIN" maxLength={2048}/></div><div className="xray-destination"><span><Globe2 size={16}/>Discovery<strong>Amazon US</strong></span><ArrowRight size={15}/><span><span className="nigeria-flag"/>Destination<strong>Nigeria</strong></span></div>{error&&<div className="form-error" role="alert">{error}</div>}<button className="button primary full" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<ScanLine size={17}/>} {busy?'Creating investigation…':'Start investigation'}<ArrowRight size={16}/></button><p className="form-caption">Identifiers are captured without fetching arbitrary URLs. Source availability determines what we can verify.</p></form></section>
 {query.error&&<Notice kind="amber">{query.error.message}<button className="text-button" onClick={()=>void query.refetch()}>Retry</button></Notice>}
 {job&&<section className="panel job-panel" aria-live="polite"><div className="section-heading"><h2>Investigation activity</h2><span className="status-label">{job.status}</span></div><p className="muted-text">{w.demo?'Demo events describe the fixture that was loaded.':'These events come from your saved research job.'}</p><div className="job-events">{job.events.map(e=><div className="job-event" key={e.id}><span className={`event-icon ${e.status}`}>{e.status==='succeeded'?<Check size={16}/>:e.status==='unavailable'?<Info size={16}/>:<CircleDashed size={16}/>}</span><div><h4>{e.step}<span>{e.status}</span></h4><p>{e.detail}</p><time dateTime={e.at}>{dateTime(e.at)}</time></div></div>)}</div></section>}
 {job&&product&&<section className="panel confirmation"><div className="section-heading"><h2>Confirm the product</h2><TruthBadge truth={w.demo?'Demo':'User input'}/></div><Notice>Product identity is unverified by an external source. Your confirmation records what you intend to investigate; it does not verify the listing’s claims.</Notice><div className="identity-row"><span>Captured identifier</span><code>{product.asin}</code><span>Match confidence <strong>Unavailable</strong></span></div><form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await w.confirm(product.id,name);setConfirmed(true);toast.success('Product identity confirmed');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}><label>Product name<input value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={160} placeholder="Enter the product name from the listing"/></label>{confirmed?<Link to={`/products/${product.id}`} className="button primary">View product evidence<ArrowRight size={16}/></Link>:<button className="button primary" disabled={busy}>Confirm this product<Check size={16}/></button>}</form></section>}
 </div><aside className="xray-aside"><div className="panel"><div className="section-icon lime"><ShieldCheck size={23}/></div><h3>Clarity at every step.</h3><p>An investigation is useful even when the answer is “we need more evidence.”</p><div className="numbered-steps">{[['01','Resolve the product','Capture the identifier and confirm what you are investigating.'],['02','Inspect the evidence','See sources, timestamps, and any gaps in coverage.'],['03','Test your economics','Use your quotes to understand the upside and downside.']].map(([n,title,text])=><div key={n}><span>{n}</span><div><h4>{title}</h4><p>{text}</p></div></div>)}</div></div><div className="try-demo"><ScanLine size={20}/><h4>Just looking around?</h4><p>Explore a garment steamer example, from its demand signals to an investment scenario.</p><button className="text-button" onClick={async()=>{await w.enterDemo();setInput('DEMO000001');setJobId('');setDemoJob(null);}}>Load the demo input<ArrowUpRightIcon/></button></div></aside></div></>;
}
function ArrowUpRightIcon(){return <ArrowRight size={14}/>;}
